package com.twilight.aggregator;

import com.twilight.aggregator.config.FlinkConfig;
import com.twilight.aggregator.model.AccountBalance;
import com.twilight.aggregator.model.BalanceDelta;
import com.twilight.aggregator.model.ProcessEvent;
import com.twilight.aggregator.model.TokenMetrics;
import com.twilight.aggregator.model.dexTransaction.KafkaMessage;
import org.apache.flink.streaming.api.datastream.AsyncDataStream;
import java.util.concurrent.TimeUnit;

import com.twilight.aggregator.process.balance.BalanceDeltaExtractor;
import com.twilight.aggregator.process.balance.DualStreamAligner;
import com.twilight.aggregator.process.common.EventEnrichmentMap;
import com.twilight.aggregator.process.common.RedisTokenMetricsBroadcaster;
import com.twilight.aggregator.process.common.UnifiedFilterOperator;
import com.twilight.aggregator.sink.AccountBalanceSink;
import com.twilight.aggregator.source.RedisTokenMetricsSource;
import com.twilight.aggregator.deserializer.AccountBalanceDeserializer;
import com.twilight.aggregator.serialization.KafkaMessageDeserializer;
import org.apache.flink.api.common.eventtime.WatermarkStrategy;
import org.apache.flink.contrib.streaming.state.RocksDBStateBackend;
import org.apache.flink.connector.kafka.source.KafkaSource;
import org.apache.flink.connector.kafka.source.enumerator.initializer.OffsetsInitializer;
import org.apache.flink.runtime.state.StateBackend;
import org.apache.flink.streaming.api.datastream.DataStream;
import org.apache.flink.streaming.api.datastream.BroadcastStream;
import org.apache.flink.streaming.api.datastream.ConnectedStreams;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.api.java.tuple.Tuple3;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.apache.flink.api.common.typeinfo.Types;
import java.time.Duration;
import java.util.Map;

/**
 * Account Balance Flink Job - 带价格增强的账户余额处理器
 * 
 * 标准化流程：
 * 1. 每分钟生成账户余额快照
 * 2. KafkaMessage -> UnifiedFilterOperator -> ProcessEvent (余额相关事件)
 * 3. ProcessEvent -> AsyncEventEnrichmentProcessor -> ProcessEvent (异步查询元数据)
 * 4. ProcessEvent -> RedisTokenMetricsBroadcaster -> ProcessEvent (广播Token价格指标)
 * 5. ProcessEvent -> BalanceDeltaExtractor -> BalanceDelta
 * 6. 双流对齐处理，确保数据一致性
 * 7. 将数据写入ClickHouse（包含价格信息）
 */
public class AccountBalanceJob {
    private static final Logger log = LoggerFactory.getLogger(AccountBalanceJob.class);
    
    public static void main(String[] args) throws Exception {
        // 设置执行环境
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        
        // 获取配置
        FlinkConfig config = FlinkConfig.getInstance();
        
        // 配置检查点和状态后端
        // env.enableCheckpointing(30000); // 30秒checkpoint
        // env.setRestartStrategy(RestartStrategies.fixedDelayRestart(3, org.apache.flink.api.common.time.Time.seconds(10)));
        
        // 使用RocksDB状态后端
        StateBackend stateBackend = new RocksDBStateBackend("file:///tmp/flink-rocksdb");
        env.setStateBackend(stateBackend);
        
        log.info("🚀 Starting AccountBalanceJob with price enrichment:");
        log.info("   Kafka servers: {}", config.getKafkaBootstrapServers());
        log.info("   ClickHouse URL: {}", config.getClickHouseUrl());
        log.info("   Price refresh interval: {}ms", config.getPriceRefreshInterval());
        log.info("   State backend: RocksDB");
        
        // === 数据流1: 快照流 ===
        log.info("📸 Setting up snapshot stream from Kafka...");
        
        // Kafka Source for snapshots (generated by Go service)
        KafkaSource<AccountBalance> snapshotKafkaSource = KafkaSource.<AccountBalance>builder()
            .setBootstrapServers(config.getKafkaBootstrapServers())
            .setTopics("account_balance_snapshot")
            .setGroupId("snapshot-consumer-group")
            .setStartingOffsets(OffsetsInitializer.latest())
            .setValueOnlyDeserializer(new AccountBalanceDeserializer())
            .build();
            
        DataStream<AccountBalance> snapshotStream = env
            .fromSource(snapshotKafkaSource, WatermarkStrategy.<AccountBalance>forBoundedOutOfOrderness(Duration.ofSeconds(5)), "Kafka Snapshot Source")
            .name("Kafka Snapshot Source")
            .uid("snapshot-source");
        
        // === 数据流2: 增量流 ===
        log.info("📊 Setting up delta stream...");
        
        // Kafka Source配置
        KafkaSource<KafkaMessage> kafkaSource = KafkaSource.<KafkaMessage>builder()
            .setBootstrapServers(config.getKafkaBootstrapServers())
            .setTopics("dex_transaction")
            .setGroupId(config.getKafkaGroupIdBalance())
            .setStartingOffsets(OffsetsInitializer.latest())
            .setValueOnlyDeserializer(new KafkaMessageDeserializer())
            .build();
        
        // ===== 标准化增量处理流程 =====
        WatermarkStrategy<KafkaMessage> kafkaWatermarkStrategy = WatermarkStrategy
            .<KafkaMessage>forBoundedOutOfOrderness(Duration.ofSeconds(5))
            .withTimestampAssigner((message, timestamp) -> {
                Long msgTimestamp = message.getTransaction().getTimestamp();
                return msgTimestamp != null ? msgTimestamp : System.currentTimeMillis();
            })
            .withIdleness(Duration.ofSeconds(5));
            
        WatermarkStrategy<ProcessEvent> processEventWatermarkStrategy = WatermarkStrategy
            .<ProcessEvent>forBoundedOutOfOrderness(Duration.ofSeconds(5))
            .withTimestampAssigner((event, timestamp) -> {
                Long eventTimestamp = event.getTimestamp();
                return eventTimestamp != null ? eventTimestamp : System.currentTimeMillis();
            })
            .withIdleness(Duration.ofSeconds(5));
        
        // Step 1: 统一事件过滤 (余额相关事件)
        log.info("🔧 Setting up unified event filtering for balance tracking");
        DataStream<ProcessEvent> filteredEventStream = env
            .fromSource(kafkaSource, kafkaWatermarkStrategy, "Kafka Transaction Source")
            .flatMap(UnifiedFilterOperator.Factory.forBalanceTracking())
            .name("Unified Filter Operator")
            .assignTimestampsAndWatermarks(processEventWatermarkStrategy);
        
        // Step 2: 异步元数据增强
        log.info("🔧 Setting up async metadata enrichment");
        DataStream<ProcessEvent> metadataEnrichedStream =filteredEventStream.map(new EventEnrichmentMap()).name("Event Enrichment Map");
        // Step 3: Token指标广播流设置
        log.info("🔧 Setting up Redis token metrics broadcast stream");
        RedisTokenMetricsSource metricsSource = new RedisTokenMetricsSource(config.getPriceRefreshInterval());
        BroadcastStream<Map<String, TokenMetrics>> metricsBroadcastStream = env
            .addSource(metricsSource)
            .setParallelism(1)
            .name("Redis Token Metrics Source")
            .broadcast(RedisTokenMetricsBroadcaster.TOKEN_METRICS_STATE_DESCRIPTOR);
        
        // Step 4: Token指标增强
        log.info("🔧 Setting up token metrics enrichment with broadcast");
        DataStream<ProcessEvent> enrichedEventStream = metadataEnrichedStream
            .connect(metricsBroadcastStream)
            .process(new RedisTokenMetricsBroadcaster())
            .name("Redis Token Metrics Broadcaster");
        
        // Step 5: 余额增量提取
        log.info("🔧 Setting up balance delta extraction");
        DataStream<BalanceDelta> deltaStream = enrichedEventStream
            .flatMap(new BalanceDeltaExtractor())
            .name("Balance Delta Extractor");
        
        // === 双流对齐处理（价格增强） ===
        log.info("🔄 Setting up price-aware dual stream alignment...");
        
        ConnectedStreams<AccountBalance, BalanceDelta> connectedStreams = snapshotStream
        .keyBy(
            (AccountBalance snapshot) -> Tuple3.of(
                snapshot.getAccountId(),
                snapshot.getAssetType(),
                snapshot.getBizId()
            ),
            Types.TUPLE(Types.LONG, Types.STRING, Types.LONG)   // 显式类型声明
        )
        .connect(
            deltaStream.keyBy(
                (BalanceDelta delta) -> Tuple3.of(
                    delta.getAccountId(),
                    delta.getAssetType(),
                    delta.getBizId()
                ),
                Types.TUPLE(Types.LONG, Types.STRING, Types.LONG)  // 显式类型声明
            )
        );
    
    // 应用双流对齐处理器
    DataStream<AccountBalance> alignedStream = connectedStreams
        .process(DualStreamAligner.create())
        .name("Dual Stream Aligner")
        .uid("dual-stream-aligner");
        
        // === 输出到ClickHouse ===
        log.info("💾 Setting up ClickHouse sink...");
        
        // 统一输出到同一张表
        alignedStream
            .addSink(AccountBalanceSink.create(200, 10000)) // 200条批量，10秒刷新
            .name("Account Balance Sink")
            .uid("account-balance-sink");
        
        // === 启动作业 ===
        log.info("✅ Pipeline setup completed");
        log.info("📊 AccountBalanceJob pipeline summary:");
        log.info("  ├─ Kafka Snapshot Source (account_balance_snapshot)");
        log.info("  ├─ Kafka Transaction Source (dex_transaction)");
        log.info("  ├─ Balance Delta Extractor");
        log.info("  ├─ Redis Price Source (token_price:*)");
        log.info("  ├─ BalanceDelta Price Broadcaster (price enrichment)");
        log.info("  ├─ Dual Stream Aligner (snapshot + enriched delta)");
        log.info("  └─ ClickHouse Sink (account_balance with prices)");
        log.info("🚀 Starting job execution: Account Balance Processing Job with Price Enrichment");
        env.execute("Account Balance Processing Job with Price Enrichment");
    }
}
